spring:
  application:
    name:
      api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: oauth2-login
            uri: http://localhost:8082
            predicates:
              - Path=/authenticate
          - id: oauth2-resource-server
            uri: http://localhost:8081
            predicates:
              - Path=/test

server:
  port: 9090